Document: telkkarista-dl
Title: Debian telkkarista-dl Manual
Author: <insert document author here>
Abstract: This manual describes what telkkarista-dl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/telkkarista-dl/telkkarista-dl.sgml.gz

Format: postscript
Files: /usr/share/doc/telkkarista-dl/telkkarista-dl.ps.gz

Format: text
Files: /usr/share/doc/telkkarista-dl/telkkarista-dl.text.gz

Format: HTML
Index: /usr/share/doc/telkkarista-dl/html/index.html
Files: /usr/share/doc/telkkarista-dl/html/*.html
